bot:
  admins: [1320607880]
  db_url: sqlite+aiosqlite:///bot/data.db
  ttl_default: 5

ws:
  url: wss://ws-api.oneme.ru/websocket

logging:
  format: '%(asctime)s | %(name)s | %(levelname)s | %(message)s'
  date_format: '%Y-%m-%d %H:%M:%S'
